#!/usr/bin/env python3

#  OpenSoccerManager
#
#  Copyright 2015 Andrew Steele <andrew.steele@opensoccermanager.org>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.


from gi.repository import Gtk
import os

from uigtk import window

import database
import dialogs
import game
import music
import preferences


game.database = database.Database()
game.database = game.database.get_database_object()

game.continuegame = game.ContinueGame()
preferences.preferences = preferences.Preferences()
music.music = music.Player()

game.window = window.Window()
window.window = game.window
game.window.run()

dialogs.comparison = dialogs.Comparison()


if __name__ == "__main__":
    Gtk.main()
